/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.mobile.view;

import ec.edu.espe.mobile.controller.FormsHandler;
import ec.edu.espe.mobile.view.FrmAbout;
import ec.edu.espe.mobile.view.FrmAbout;
import ec.edu.espe.mobile.view.FrmAccount;
import ec.edu.espe.mobile.view.FrmAccount;
import ec.edu.espe.mobile.view.FrmCashAvaliable;
import ec.edu.espe.mobile.view.FrmCashAvaliable;
import ec.edu.espe.mobile.view.FrmContacTeacher;
import ec.edu.espe.mobile.view.FrmContacTeacher;
import ec.edu.espe.mobile.view.FrmHelp;
import ec.edu.espe.mobile.view.FrmHelp;
import ec.edu.espe.mobile.view.FrmHistory;
import ec.edu.espe.mobile.view.FrmHistory;
import ec.edu.espe.mobile.view.FrmInteractiveMap;
import ec.edu.espe.mobile.view.FrmInteractiveMap;
import ec.edu.espe.mobile.view.FrmJoinClass;
import ec.edu.espe.mobile.view.FrmJoinClass;
import ec.edu.espe.mobile.view.FrmPayTuition;
import ec.edu.espe.mobile.view.FrmPayTuition;

/**
 *
 * @author Raúl Silva
 */
public class FrmEspeMobileStudent extends javax.swing.JFrame {

    /**
     * Creates new form FrmEspeMobileApp
     */
    public FrmEspeMobileStudent() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuStuMenu = new javax.swing.JMenu();
        itmMainm = new javax.swing.JMenuItem();
        itmExitS = new javax.swing.JMenuItem();
        mnuSocialAcount = new javax.swing.JMenu();
        itmAccount = new javax.swing.JMenu();
        itmAddClass = new javax.swing.JMenuItem();
        itmSetting = new javax.swing.JMenuItem();
        itmContact = new javax.swing.JMenuItem();
        itmJoin = new javax.swing.JMenuItem();
        itmMap = new javax.swing.JMenu();
        itmEnterMap = new javax.swing.JMenuItem();
        mnuPaymentTracker = new javax.swing.JMenu();
        itmCash = new javax.swing.JMenuItem();
        itmPay = new javax.swing.JMenuItem();
        itmHistory = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/mobile/view/Estudiante (1).png"))); // NOI18N
        jLabel2.setText(".");

        mnuStuMenu.setText("Espe Mobile App");

        itmMainm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmMainm.setText("Main menu");
        itmMainm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMainmActionPerformed(evt);
            }
        });
        mnuStuMenu.add(itmMainm);

        itmExitS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        itmExitS.setText("Exit");
        itmExitS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExitSActionPerformed(evt);
            }
        });
        mnuStuMenu.add(itmExitS);

        jMenuBar1.add(mnuStuMenu);

        mnuSocialAcount.setText("Social Account");

        itmAccount.setText("Account");

        itmAddClass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmAddClass.setText("Add Classmate");
        itmAddClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddClassActionPerformed(evt);
            }
        });
        itmAccount.add(itmAddClass);

        itmSetting.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmSetting.setText("Settings");
        itmSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSettingActionPerformed(evt);
            }
        });
        itmAccount.add(itmSetting);

        mnuSocialAcount.add(itmAccount);

        itmContact.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmContact.setText("Contact Teacher");
        itmContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmContactActionPerformed(evt);
            }
        });
        mnuSocialAcount.add(itmContact);

        itmJoin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmJoin.setText("Join Class");
        itmJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmJoinActionPerformed(evt);
            }
        });
        mnuSocialAcount.add(itmJoin);

        jMenuBar1.add(mnuSocialAcount);

        itmMap.setText("Interactive Map");

        itmEnterMap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmEnterMap.setText("Enter to the map");
        itmEnterMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEnterMapActionPerformed(evt);
            }
        });
        itmMap.add(itmEnterMap);

        jMenuBar1.add(itmMap);

        mnuPaymentTracker.setText("Payment Tracker");

        itmCash.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCash.setText("Cash Available");
        itmCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCashActionPerformed(evt);
            }
        });
        mnuPaymentTracker.add(itmCash);

        itmPay.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmPay.setText("Pay Tuition");
        itmPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPayActionPerformed(evt);
            }
        });
        mnuPaymentTracker.add(itmPay);

        itmHistory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmHistory.setText("History Payment");
        itmHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmHistoryActionPerformed(evt);
            }
        });
        mnuPaymentTracker.add(itmHistory);

        jMenuBar1.add(mnuPaymentTracker);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmContactActionPerformed
        FrmContacTeacher frmContacTeacher = new FrmContacTeacher();
        frmContacTeacher.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmContactActionPerformed

    private void itmJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmJoinActionPerformed
        FrmJoinClass frmJoinClass = new FrmJoinClass();
        frmJoinClass.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmJoinActionPerformed

    private void itmEnterMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEnterMapActionPerformed
        FrmStudentMap frmStudentMap  = new FrmStudentMap ();
        frmStudentMap .setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmEnterMapActionPerformed

    private void itmCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCashActionPerformed
        FrmCashAvaliable frmCashAvaliable = new FrmCashAvaliable();
        frmCashAvaliable.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmCashActionPerformed

    private void itmPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPayActionPerformed
        FrmPayTuition frmPayTuition = new FrmPayTuition();
        frmPayTuition.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmPayActionPerformed

    private void itmHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmHistoryActionPerformed
        FrmHistory frmHistory = new FrmHistory();
        frmHistory.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmHistoryActionPerformed

    private void itmMainmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMainmActionPerformed
         FormsHandler.goToMainScreen(this);
    }//GEN-LAST:event_itmMainmActionPerformed

    private void itmExitSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitSActionPerformed
         this.dispose();
    }//GEN-LAST:event_itmExitSActionPerformed

    private void itmSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSettingActionPerformed
        FrmAccount frmAccount = new FrmAccount();
        frmAccount.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmSettingActionPerformed

    private void itmAddClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddClassActionPerformed
        FrmAddClassmate frmAddClassmate = new FrmAddClassmate();
        frmAddClassmate.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmAddClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEspeMobileStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEspeMobileStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEspeMobileStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEspeMobileStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEspeMobileStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itmAccount;
    private javax.swing.JMenuItem itmAddClass;
    private javax.swing.JMenuItem itmCash;
    private javax.swing.JMenuItem itmContact;
    private javax.swing.JMenuItem itmEnterMap;
    private javax.swing.JMenuItem itmExitS;
    private javax.swing.JMenuItem itmHistory;
    private javax.swing.JMenuItem itmJoin;
    private javax.swing.JMenuItem itmMainm;
    private javax.swing.JMenu itmMap;
    private javax.swing.JMenuItem itmPay;
    private javax.swing.JMenuItem itmSetting;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu mnuPaymentTracker;
    private javax.swing.JMenu mnuSocialAcount;
    private javax.swing.JMenu mnuStuMenu;
    // End of variables declaration//GEN-END:variables
}
