/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.mobile.view;

import ec.edu.espe.mobile.controller.FormsHandler;
import ec.edu.espe.mobile.view.FrmAbout;
import ec.edu.espe.mobile.view.FrmAccount;
import ec.edu.espe.mobile.view.FrmFilter;
import ec.edu.espe.mobile.view.FrmFindStudent;
import ec.edu.espe.mobile.view.FrmHelp;
import ec.edu.espe.mobile.view.FrmInteractiveMap;
import ec.edu.espe.mobile.view.FrmJoinClass;
import ec.edu.espe.mobile.view.FrmStudentList;

/**
 *
 * @author Juan Diego
 */
public class FrmEspeMobileTeacher extends javax.swing.JFrame {

    /**
     * Creates new form FrmEspeMobileApp
     */
    public FrmEspeMobileTeacher() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuEspeMobileApp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        itmExit = new javax.swing.JMenuItem();
        mnuSocialAcount = new javax.swing.JMenu();
        itmAcounteach = new javax.swing.JMenu();
        itmASettingteach = new javax.swing.JMenuItem();
        itmFinds = new javax.swing.JMenuItem();
        itmJoin = new javax.swing.JMenuItem();
        itmMapteach = new javax.swing.JMenu();
        itmEnterMap = new javax.swing.JMenuItem();
        mnuFilter = new javax.swing.JMenu();
        itmList = new javax.swing.JMenuItem();
        itmFilter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/mobile/view/Maestro.png"))); // NOI18N
        jLabel2.setText(".");

        mnuEspeMobileApp.setText("Espe Mobile App");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuEspeMobileApp.add(jMenuItem1);

        itmExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        itmExit.setText("Exit");
        itmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExitActionPerformed(evt);
            }
        });
        mnuEspeMobileApp.add(itmExit);

        jMenuBar1.add(mnuEspeMobileApp);

        mnuSocialAcount.setText("Social Account");

        itmAcounteach.setText("Account");

        itmASettingteach.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmASettingteach.setText("Account Settings");
        itmASettingteach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmASettingteachActionPerformed(evt);
            }
        });
        itmAcounteach.add(itmASettingteach);

        itmFinds.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmFinds.setText("Find Student");
        itmFinds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmFindsActionPerformed(evt);
            }
        });
        itmAcounteach.add(itmFinds);

        mnuSocialAcount.add(itmAcounteach);

        itmJoin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmJoin.setText("Join Class");
        itmJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmJoinActionPerformed(evt);
            }
        });
        mnuSocialAcount.add(itmJoin);

        jMenuBar1.add(mnuSocialAcount);

        itmMapteach.setText("Interactive Map");

        itmEnterMap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmEnterMap.setText("Enter to the map");
        itmEnterMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEnterMapActionPerformed(evt);
            }
        });
        itmMapteach.add(itmEnterMap);

        jMenuBar1.add(itmMapteach);

        mnuFilter.setText("Student Filter");

        itmList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmList.setText("List");
        itmList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListActionPerformed(evt);
            }
        });
        mnuFilter.add(itmList);

        itmFilter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmFilter.setText("Filter");
        itmFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmFilterActionPerformed(evt);
            }
        });
        mnuFilter.add(itmFilter);

        jMenuBar1.add(mnuFilter);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
       this.dispose();
    }//GEN-LAST:event_itmExitActionPerformed

    private void itmJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmJoinActionPerformed
        FrmJoinClassTeach frmJoinClassTeach = new FrmJoinClassTeach();
        frmJoinClassTeach.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmJoinActionPerformed

    private void itmEnterMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEnterMapActionPerformed
        FrmInteractiveMap frmInteractiveMap  = new FrmInteractiveMap ();
        frmInteractiveMap .setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmEnterMapActionPerformed

    private void itmListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListActionPerformed
        FrmStudentList frmStudentList = new FrmStudentList();
        frmStudentList.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmListActionPerformed

    private void itmASettingteachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmASettingteachActionPerformed
        FrmAccountTeach frmAccountTeach = new FrmAccountTeach();
        frmAccountTeach.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmASettingteachActionPerformed

    private void itmFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmFilterActionPerformed
        FrmFilter frmFilter = new FrmFilter();
        frmFilter.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmFilterActionPerformed

    private void itmFindsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmFindsActionPerformed
        FrmFindStudent frmFindt = new FrmFindStudent();
        frmFindt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmFindsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormsHandler.goToMainScreen(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEspeMobileTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEspeMobileTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEspeMobileTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEspeMobileTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEspeMobileTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmASettingteach;
    private javax.swing.JMenu itmAcounteach;
    private javax.swing.JMenuItem itmEnterMap;
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmFilter;
    private javax.swing.JMenuItem itmFinds;
    private javax.swing.JMenuItem itmJoin;
    private javax.swing.JMenuItem itmList;
    private javax.swing.JMenu itmMapteach;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuEspeMobileApp;
    private javax.swing.JMenu mnuFilter;
    private javax.swing.JMenu mnuSocialAcount;
    // End of variables declaration//GEN-END:variables
}
